rvm: 
  - 1.8.7
  - 1.9.3-p484
bundler_args: ''
notifications:
  email:
  - tfhartmann@gmail.com
  hipchat:
    rooms:
      secure: gChdWNxhZ4XQS+We5d4XRxz53shln62wz45OTa5teBZP+6Urhwv4ZmOa+F7LHJLytcnS40R8CWaKXXmdo8e+yKIKpJjvIAlSNDT7wSPb4uL+bJZEQDfkQ6Oknliuzy6tP9Dy62Z9Ms4IH58QA6zfOj9ibxb6r9/2XRFSuVZAMN4=
env:
- PUPPET_VERSION=3.4.2
- PUPPET_VERSION=3.3.1
- PUPPET_VERSION=3.2.3
- PUPPET_VERSION=2.7.21
